### Word Embedding

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Define the vocabulary size
voc_size = 10000

In [6]:
# One hot representation for every word
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2557, 3179, 7785, 1902],
 [2557, 3179, 7785, 5987],
 [2557, 2056, 7785, 6704],
 [9213, 2899, 6358, 2132, 9533],
 [9213, 2899, 6358, 2132, 6173],
 [5426, 2557, 645, 7785, 1960],
 [7725, 4380, 3676, 2132]]

In [ ]:
# Word embedding representations

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
# embedded_docs = pad_sequences(one_hot_repr, padding='post', maxlen=sent_length)

embedded_docs

array([[   0,    0,    0,    0, 2557, 3179, 7785, 1902],
       [   0,    0,    0,    0, 2557, 3179, 7785, 5987],
       [   0,    0,    0,    0, 2557, 2056, 7785, 6704],
       [   0,    0,    0, 9213, 2899, 6358, 2132, 9533],
       [   0,    0,    0, 9213, 2899, 6358, 2132, 6173],
       [   0,    0,    0, 5426, 2557,  645, 7785, 1960],
       [   0,    0,    0,    0, 7725, 4380, 3676, 2132]])

In [12]:
# Feature represenation
dim = 10

In [13]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))

model.compile('adam', 'mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 160ms/step


array([[[-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
         -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
         -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
         -4.72069867e-02],
        [-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
         -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
         -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
         -4.72069867e-02],
        [-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
         -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
         -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
         -4.72069867e-02],
        [-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
         -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
         -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
         -4.72069867e-02],
        [-1.62981264e-02, -2.08657272e-02, -2.55182870e-02,
         -2.59793755e-02,  1.44929029e-02, -2.11339947e-02,
         -2.04624534e-02,  4.16757911e-03,  2.913859

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 2557, 3179, 7785, 1902])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 34ms/step


array([[-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
        -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
        -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
        -4.72069867e-02],
       [-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
        -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
        -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
        -4.72069867e-02],
       [-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
        -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
        -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
        -4.72069867e-02],
       [-1.08107924e-05, -1.66293271e-02,  2.59600915e-02,
        -4.76460569e-02,  4.57195975e-02, -2.65678298e-02,
        -4.54295166e-02, -3.99932154e-02,  3.05203348e-03,
        -4.72069867e-02],
       [-1.62981264e-02, -2.08657272e-02, -2.55182870e-02,
        -2.59793755e-02,  1.44929029e-02, -2.11339947e-02,
        -2.04624534e-02,  4.16757911e-03,  2.91385986e-02,
        -2.

In [25]:
model.predict(one_hot('Hi hello yes', 10000))

1/1 [==============================] - 0s 31ms/step


array([[-0.01493101,  0.0333918 ,  0.04978431,  0.04849592,  0.00870992,
        -0.00436106,  0.04032521,  0.02280561,  0.00067652, -0.01542988],
       [ 0.04052922, -0.00663667, -0.0265609 ,  0.03467181, -0.00608031,
        -0.02616818,  0.00210905,  0.00595317,  0.00570538, -0.00865052],
       [-0.02539916,  0.04425904,  0.02801264, -0.01841522,  0.04805679,
        -0.0490795 ,  0.03152778, -0.04081268, -0.01412389, -0.04244364]],
      dtype=float32)